name: project
description: A Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  meta: ^1.8.0
  riverpod_annotation: ^1.1.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  riverpod_generator: ^1.1.1

flutter:
  uses-material-design: true
